config/routes.rb
Rails.application.routes.draw do
 

  

  scope "(:locale)", locale: /en|fr/ do
  
  resources :plans 
       
  resources :subscriptions
   

  resources :interiordesigners do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :countertops do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :customcabinets do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :cashbuyers do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :movingcompanies do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :poolrepairs do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :poolcleaners do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :solarscreens do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :windows do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :termiteinspectors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :taxspecialists do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :titlecompanies do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :septics do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :securities do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :stagings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :rentalproperties do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :accountants do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :lawyers do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :real_estatefirms do 
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :realtors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :roofings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :privatebanks do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :privatefirms do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :propertymanagementfirms do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :paintings do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :plumbings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :molds do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :mortgages do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :landsurveyors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :landscapings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :insulations do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :hardmoneys do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :homeinspectors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :generalcontractors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :floorings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :framings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :drywalls do
      collection do
      get 'search'
      get :autocomplete
    end
  end
  resources :orders
  
  devise_for :users
  resources :subscriptionpackages do
    resources :orders
  end
  resources :asphalts do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :airconditioners do
    collection do
      get 'search'
    get :autocomplete
    end
  end  

  resources :services do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :arquitects do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  

  

 
  resources :commercialpropertiesforsales do
    collection do
      get 'search'
    end
  end
  
  resources :service_types

  resources :residentials do
    collection do
      get 'search'
      get 'bedrooms'
      get :autocomplete
    end
  end

  get 'pages/home'

  get 'pages/membership'
  get 'pages/privacypolicy'
  get 'pages/termsofuse'

  get 'pages/contactus'
  get 'pages/realestateservices'
  get 'seller' => "subscriptionpackages#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'pages#home'

end

end

app/models/asphalt.rb
class Asphalt < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "200x>", :thumb => "100x100>" }, :default_url => "default.jpg",
			
	:storage => :dropbox,
      :dropbox_credentials => Rails.root.join("config/dropbox.yml")
      validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	searchkick autocomplete: ['query']
end

app/controllers/asphalts_controller.rb
class AsphaltsController < ApplicationController
  before_action :set_asphalt, only: [:show, :edit, :update, :destroy]
  

def search
    if params[:search].present?
     @asphalts = Asphalt.search(params[:search])
    else
      @asphalts = Asphalt.all
    end
  end

  def autocomplete
    render json: Asphalt.search(params[:query], fields:[{name: :text_start}], limit: 10).map(&:name)
  end


  def index
    @asphalts = Asphalt.all
    
  end

  def show
    
  end

  def new
    @asphalt = Asphalt.new
   
  end

  def edit
  end

  def create
     @asphalt = Asphalt.new(asphalt_params)
    respond_to do |format|
      if @asphalt.save
        format.html { redirect_to  @asphalt, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location:  @asphalt }
      else
        format.html { render :new }
        format.json { render json:  @asphalt.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @asphalt.update(asphalt_params)
        format.html { redirect_to @asphalt, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @asphalt }
      else
        format.html { render :edit }
        format.json { render json: @asphalt.errors, status: :unprocessable_entity }
      end
    end

  end

  def destroy
    @asphalt.destroy
    respond_to do |format|
      format.html { redirect_to asphalt_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_asphalt
      @asphalt = Asphalt.find(params[:id])
    end

    def asphalt_params
      params.require(:asphalt).permit(:company_name, :company_description, :address, :city, :zipcode, :contact_name, :company_website, :company_phone, :image)
    end
end

app/helpers/asphalts_helper.rb
module AsphaltsHelper
end

app/views/asphalts/_form.html.erb
<%= form_for(@asphalt,:html => { :multipart => true }) do |f| %>
  <% if @asphalt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asphalt.errors.count, "error") %> prohibited this asphalt from being saved:</h2>

      <ul>
      <% @asphalt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="thumbnail">
  <div class="row">
    <div class="col-md-4">
      <%= f.label :company_name %><br>
      <%= f.text_field :company_name, class: "form-control"  %><br>
    </div>
    
    <div class="col-md-4">
      <%= f.label :company_description %><br>
      <%= f.text_area :company_description, class: "form-control"  %><br>
    </div>
    <div class="col-md-4">
      <%= f.label :address %><br>
      <%= f.text_area :address, class: "form-control"  %><br>
    </div>
    <div class="col-md-4">
      <%= f.label :city %><br>
      <%= f.text_field :city, class: "form-control"  %><br>
    </div>
    <div class="col-md-4">
      <%= f.label :zipcode %><br>
      <%= f.text_field :zipcode, class: "form-control"  %><br>
    </div>
    <div class="col-md-4">
       <%= f.label :contact_name %><br>
       <%= f.text_field :contact_name, class: "form-control"  %><br>
    </div>
    <div class="col-md-4">
      <%= f.label :company_website %><br>
      <%= f.text_field :company_website, class: "form-control"  %><br>
    </div>
    <div class="col-md-4">
      <%= f.label :company_phone %><br>
      <%= f.text_field :company_phone, class: "form-control"  %><br>
    </div>
    <div class="col-md-4">
    <%= f.label :pictures %>  <%= f.file_field :image, class: "form-control" %><br><br>
    </div>
  
  
  <div class="col-md-4">
    <%= f.submit "Create a Asphalt Service", class: "btn btn-warning" %>
  </div>
  <br>
 
<% end %>
 </div>
</div>

app/views/asphalts/edit.html.erb
<div class="jumbotron">
  <div class="left">
    <%= t('jumbotron_asphalttitle_html') %>
  
 </div>
 </div>


<%= render 'form' %>

<%= link_to 'Show', @asphalt, class: "btn btn-link" %> |
<%= link_to t('back'), asphalts_path, class: "btn btn-link" %>

app/views/asphalts/index.html.erb
<div class="jumbotron">
  <div class="left">
    <%= t('jumbotron_asphalttitle_html') %>
  
 </div>
 </div>

<div class="left"> 
    <%= t('searchservice_html') %>
   <%= form_tag search_asphalts_path, method: :get do %>
          <p>
        <%= text_field :search, params[:search], placeholder: t('searchtextbox') class: "form-control" %>
        <br>
         <%= submit_tag t('searchbtn'), name: nil ,class: "btn btn-success" %>
      </p>
    </div>
  <% end %>



<div class="thumbnail">
  <div class="center"> 
    <div class="row">
    <% @asphalts.each do |asphalt| %>
      <div class="col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag(asphalt.image.url), asphalt %>
        <div class="caption">
          <h4><strong><%= asphalt.company_name %></strong></h4>
          <strong><th><%= label_tag :nil, t('servicecompanywebsite') %></th></strong><br>
            <%= link_to asphalt.company_website, asphalt.company_website %><br>
            <strong><th><%= label_tag :nil, t('servicecompanyphone') %></th></strong><br>
            <%= asphalt.company_phone %><br>
           <strong><th><%= label_tag :nil, t('servicecompanyaddress') %></th></strong><br>
           <%= asphalt.address %><br> 
           <strong><th><%= label_tag :nil, t('city') %></th></strong><%= asphalt.city %><br>
           <strong><th><%= label_tag :nil, t('zipcode') %></th></strong><br><%= asphalt.zipcode %><br>
           <br>
           
           <td><%= link_to 'Show', asphalt, class: "btn btn-success" %></td>
        
        <td><%= link_to 'Edit', edit_asphalt_path(asphalt), class: "btn btn-success" %></td>
        <td><%= link_to 'Destroy', asphalt, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-success" %></td>
        </div>
      </div>
    </div>
    <% end %>
    </div>

  </div>
</div>   
   

<br>
<br>
<% if user_signed_in? && current_user.admin? %>
<%= link_to t('add_service'), new_asphalt_path, class: "btn btn-success" %>
<% end %>

app/views/asphalts/new.html.erb
<div class="jumbotron">
  <div class="left">
    <%= t('jumbotron_asphalttitle_html') %>
  
 </div>
 </div>



<%= render 'form' %>

<%= link_to t('back'), asphalts_path, class: "btn btn-link" %>

app/views/asphalts/search.html.erb
<%= t('searchresults_html') %>
<div class="thumbnail">
  <div class="center"> 
    <div class="row">
     <% @asphalts.each do |asphalt| %>
      <div class="col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag(asphalt.image.url), asphalt %>
        <div class="caption">
          <h4><strong><%= asphalt.company_name %></strong></h4>
          <strong><th><%= label_tag :nil, t('servicecompanywebsite') %></th></strong><br>
            <%= link_to asphalt.company_website, asphalt.company_website %><br>
            <strong><th><%= label_tag :nil, t('servicecompanyphone') %></th></strong><br>
            <%= asphalt.company_phone %><br>
           <strong><th><%= label_tag :nil, t('servicecompanyaddress') %></th></strong><br>
           <%= asphalt.address %><br> 
           <strong><th><%= label_tag :nil, t('city') %></th></strong><%= asphalt.city %><br>
           <strong><th><%= label_tag :nil, t('zipcode') %></th></strong><br><%= asphalt.zipcode %><br>
           <br>
           
           <td><%= link_to 'Show', asphalt, class: "btn btn-success" %></td>
        
        <td><%= link_to 'Edit', edit_asphalt_path(asphalt), class: "btn btn-success" %></td>
        <td><%= link_to 'Destroy', asphalt, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-success" %></td>
        </div>
      </div>
    </div>
    <% end %>
    </div>

  </div>
</div>
   

<br>
<br>

<%= link_to t('back'), asphalts_path, class: "btn btn-link" %>

app/views/asphalts/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
       <%= image_tag @asphalt.image.url %>
       <br> 
      <strong><%= @asphalt.company_name %></strong>
      <br>
      <br>
      <strong><%= label_tag :nil, t('servicecompanywebsite') %></strong>  
      <%= link_to @asphalt.company_website, @asphalt.company_website %><br>
      
      
      <strong><%= label_tag :nil, t('companycontactname') %></strong>  
     <%= @asphalt.contact_name %>
     <br>
      <strong><%= label_tag :nil, t('companyservicephone') %></strong> 
     <%= @asphalt.company_phone %><br>
     <strong><%= label_tag :nil, t('servicecompanyaddress') %></strong>  
     <%= @asphalt.address %><br>
      <strong><%= label_tag :nil, t('city') %></strong>  
     <%= @asphalt.city %><br>
     <strong><%= label_tag :nil, t('zipcode') %></strong>  
     <%= @asphalt.zipcode %><br>
    </div>
     <br>

  </div>
  <div class="col-md-6">
    <h5><strong><%= label_tag :nil, t('generalcompany') %></strong></h5>
    <%= @asphalt.company_description %>
  </div>

</div>

  <div class ="col-md-12">
    <div class= "center">
   <strong><%= label_tag :nil, t('mapview') %></strong><br>
   <br>
<iframe
  width="800"
  height="450"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=AIzaSyAUOQ0h7ZYU56FuY9ziMMXURoIlHxC3pfY
    &q=<%= @asphalt.address.parameterize %>">
</iframe>

</div>
<br>
<br>  
 </div>



<%= link_to 'Edit', edit_asphalt_path(@asphalt), class: "btn btn-link" %> |
<%= link_to t('back'), asphalts_path, class: "btn btn-link" %>