config/routes.rb
Rails.application.routes.draw do
 

  

  scope "(:locale)", locale: /en|fr/ do
  
  resources :plans 
       
  resources :subscriptions
   

  resources :interiordesigners do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :countertops do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :customcabinets do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :cashbuyers do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :movingcompanies do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :poolrepairs do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :poolcleaners do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :solarscreens do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :windows do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :termiteinspectors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :taxspecialists do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :titlecompanies do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :septics do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :securities do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :stagings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :rentalproperties do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :accountants do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :lawyers do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :real_estatefirms do 
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :realtors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :roofings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :privatebanks do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :privatefirms do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :propertymanagementfirms do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :paintings do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :plumbings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :molds do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :mortgages do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :landsurveyors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :landscapings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :insulations do
     collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :hardmoneys do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :homeinspectors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :generalcontractors do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :floorings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :framings do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :drywalls do
      collection do
      get 'search'
      get :autocomplete
    end
  end
  resources :orders
  
  devise_for :users
  resources :subscriptionpackages do
    resources :orders
  end
  resources :asphalts do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :airconditioners do
    collection do
      get 'search'
    get :autocomplete
    end
  end  

  resources :services do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  resources :arquitects do
    collection do
      get 'search'
      get :autocomplete
    end
  end

  

  

 
  resources :commercialpropertiesforsales do
    collection do
      get 'search'
    end
  end
  
  resources :service_types

  resources :residentials do
    collection do
      get 'search'
      get 'bedrooms'
      get :autocomplete
    end
  end

  get 'pages/home'

  get 'pages/membership'
  get 'pages/privacypolicy'
  get 'pages/termsofuse'

  get 'pages/contactus'
  get 'pages/realestateservices'
  get 'seller' => "subscriptionpackages#seller"
  get 'sales' => "orders#sales"
  get 'purchases' => "orders#purchases"

  root 'pages#home'

end

end

app/models/subscriptionpackage.rb
class Subscriptionpackage < ActiveRecord::Base
	if Rails.env.development?
	has_attached_file :image, :styles => { :medium => "200x>", :thumb => "100x100>" }, :default_url => "default.jpg"
	else	
	has_attached_file :image, :styles => { :medium => "200x>", :thumb => "100x100>" }, :default_url => "default.jpg",
		:storage => :dropbox,
      	:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
      	:path => ":style/:id_:filename"
      end
      
      validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	validates :package_title, :package_name, :package_description, :price1, presence: true
	belongs_to :user
	has_many :orders
end

app/controllers/subscriptionpackages_controller.rb
class SubscriptionpackagesController < ApplicationController
  before_action :set_subscriptionpackage, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:seller]
  def seller
    @subscriptionpackages = Subscriptionpackage.where(user: current_user)
  end

  def index
    @subscriptionpackages = Subscriptionpackage.all
  end

  def show
  end

  def new
    @subscriptionpackage = Subscriptionpackage.new
  end

  def edit
  end

  def create
    @subscriptionpackage = Subscriptionpackage.new(subscriptionpackage_params)
    @subscriptionpackage.user_id = current_user.id
    
    respond_to do |format|
      if @subscriptionpackage.save
        format.html { redirect_to @subscriptionpackage, notice: 'Suscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscriptionpackage }
      else
        format.html { render :new }
        format.json { render json: @subscriptionpackage.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @subscriptionpackage.update(subscriptionpackage_params)
        format.html { redirect_to @subscriptionpackage, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscriptionpackage }
      else
        format.html { render :edit }
        format.json { render json: @subscriptionpackage.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @subscriptionpackage.destroy
    respond_to do |format|
      format.html { redirect_to @subscriptionpackage_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_subscriptionpackage
      @subscriptionpackage = Subscriptionpackage.find(params[:id])
    end

    def subscriptionpackage_params
      params.require(:subscriptionpackage).permit(:package_title, :package_name, :package_description, :price1, :features_include, :image)
    end
    def check_user
      if current_user != @subscriptionpackage.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
  end
end

app/helpers/subscriptionpackages_helper.rb
module SubscriptionpackagesHelper
end

app/views/subscriptionpackages/_form.html.erb
<%= form_for(@subscriptionpackage,:html => { :multipart => true }) do |f| %>
  <% if @subscriptionpackage.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      
      <h2><%= pluralize(@subscriptionpackage.errors.count, "error") %> prohibited this subscriptionpackage from being saved:</h2>

      <ul>
      <% @subscriptionpackage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="thumbnail">
  <div class="field">
    <div class="left">
    <%= label_tag :nil, "PROPERTY LISTING SUBSCRIPTIONS" %>
    </div>
  </div>
  <div class="form-group">
    <div class="row">
      <div class="left">
       <div class="col-md-4">
     <%= label_tag :nil, "Subscription Title:" %>
      <%= f.text_field :package_title, class: "form-control"  %><br>
      </div>
      <div class="col-md-4">
      <%= label_tag :nil, "Listing Subscription Name:" %>
      <%= f.text_field :package_name, class: "form-control"  %><br>
      </div>
      <div class="col-md-4">
      <%= label_tag :nil, "Description" %>
      <%= f.text_area :package_description, class: "form-control"  %><br>
      </div>
      </div>
    </div>
  </div>
    <div class="form-group">
    <div class="row">
      <div class="left">
       <div class="col-md-4">
      <%= label_tag :nil, "Price" %>
      <%= f.text_field :price1, class: "form-control"  %><br>
      </div>
      <div class="col-md-4">
      <%= label_tag :nil, "Additional Comments" %>
      <%= f.text_area :features_include , class: "form-control"  %><br>
    </div>
     <div class="col-md-4">
    <%= f.label :pictures %>  <%= f.file_field :image, class: "form-control" %>
    </div>
  </div>
    </div>
  </div>
  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>
</div>
 <div class="form-group">
  <div class="left">
    <%= f.submit "Subscribe", class: "btn btn-warning", data: { no_turbolink: true } %>
  </div>
</div>
<% end %>
 

app/views/subscriptionpackages/edit.html.erb
<h1>Editing Florida's Only Subscription Packages</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscriptionpackage, class: "btn btn-link" %> |
<%= link_to 'Back', subscriptionpackages_path, class: "btn btn-link" %>

app/views/subscriptionpackages/index.html.erb
<div class="thumbnail">
  <div class="center"> 
    <div class="row">
      <% @subscriptionpackages.each do |subscriptionpackage| %>
      <div class="col-md-3">
      <div class="thumbnail">
        <%= link_to image_tag(subscriptionpackage.image.url), subscriptionpackage %>
        <div class="caption">
          <h4><strong><%= subscriptionpackage.package_title %></strong></h4>
          <strong><th>Subscription Name: </th></strong><br>
            <%= subscriptionpackage.package_name %><br>
            <strong><th>Subscription Package Description: </th></strong><br>
            <%= subscriptionpackage.package_description %><br>
           <strong><th>Price: </th></strong><br>
           <%= subscriptionpackage.price %><br> 
           <strong><th>Features Include: </th></strong><%= subscriptionpackage.features_include %><br>
           <br>
           
           <td><%= link_to 'Show', subscriptionpackage, class: "btn btn-warning" %></td>
            <td><%= link_to 'Edit', edit_subscriptionpackage_path(subscriptionpackage), class: "btn btn-warning" %></td>
            <td><%= link_to 'Destroy', subscriptionpackage, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %></td>
        </div>
      </div>
    </div>
    <% end %>
    </div>

  </div>
</div>   
   

<br>


<br>

<%= link_to 'New Subscriptionpackage', new_subscriptionpackage_path, class: "btn btn-warning", data: { no_turbolink: true }  %>

app/views/subscriptionpackages/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', subscriptionpackages_path, class: "btn btn-link" %>

app/views/subscriptionpackages/seller.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th>Image</th>
    <th>Package Title</th>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Action</th>
  </tr>
<% @subscriptionpackages.each do |subscriptionpackage| %>
<tr>
  <td><%= image_tag subscriptionpackage.image.url(:thumb) %></td>
  <td><%= subscriptionpackage.package_title %></td>
  <td><%= subscriptionpackage.package_name %></td>
  <td><%= subscriptionpackage.package_description %></td>
  <td><%= subscriptionpackage.price %></td>

  <td>
    <div class="btn-group">
       <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
    
    <ul class="dropdown-menu" role="menu">
    <%= link_to 'Show', subscriptionpackage, class: "btn btn-warning" %></td>
        
        <td><%= link_to 'Edit', edit_subscriptionpackage_path(subscriptionpackage), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', subscriptionpackage, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-warning" %>
        </ul>
        </div>
        </td>

</tr>
<% end %>
</table>

<br>

<%= link_to 'New Subscriptionpackage', new_subscriptionpackage_path, class: "btn btn-warning", data: { no_turbolink: true } %>

app/views/subscriptionpackages/show.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
       <%= image_tag @subscriptionpackage.image.url %>
       <br> 
      <strong><%= @subscriptionpackage.package_title %></strong>
      <br>
      <br>
      <strong>Subscription Name:</strong>  
      <%= @subscriptionpackage.package_name %><br>
      
      
      <strong>Package Description:</strong>  
     <%= @subscriptionpackage.package_description %>
     <br>
      <strong>Price:</strong> 
     <%= @subscriptionpackage.price1 %><br>
     <br>
     <div class="center">
      <%= link_to "Buy Option to Post Listing Now", new_subscriptionpackage_order_path(@subscriptionpackage), class: "btn btn-warning", data: { no_turbolink: true } %>
     </div>
    </div>
     <br>

  </div>
  <div class="col-md-6">
    <h5><strong>Subscription Features Include:</strong></h5>
    <%= @subscriptionpackage.features_include %>
  </div>

</div>


<%= link_to 'Edit', edit_subscriptionpackage_path(@subscriptionpackage), class: "btn btn-link" %> |
<%= link_to 'Back', subscriptionpackages_path, class: "btn btn-link" %>